config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "home#index"
  get "/home", to: "home#index"
 

  resources :tables do
    resources :orders
  end

  resources :dishes
  resources :ingredients
  resources :recipes

  post "recipes/new", to: "recipes#create"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_many :recipes
  has_many :ingredients, :through => :recipes
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipes
  has_many :dishes, :through => :recipes
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :table
  has_many :dish
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :ingredient
  belongs_to :dish
end

app/models/table.rb
class Table < ApplicationRecord
  has_many :orders

  validates :number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  
  def index
    @dishes = Dish.all
  end

  def show
    @dish = Dish.find(params[:id])
    @recipe_ingredients = Recipe.find_by_sql("SELECT ingredients.name, recipes.quantity FROM recipes, ingredients WHERE recipes.ingredient_id = ingredients.id AND recipes.dish_id = ?", @dish.id)
  end

  def new
    @dish = Dish.new
  end

  def create
    @dish = Dish.new(dish_params)
    
    if @dish.save
      redirect_to @dish
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def dish_params
      params.require(:dish).permit(:name, :price)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    
    if @ingredient.save
      redirect_to @ingredient
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    @ingredient = Ingredient.find(params[:id])

    if @ingredient.update(ingredient_params)
      redirect_to @ingredient
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def ingredient_params
      params.require(:ingredient).permit(:name, :quantity)
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  def show
    @table = Table.find(params[:table_id])
    @orders = @table.order.all
  end

  def new
    Order.new
  end

  def create
    @table = Table.find(params[:table_id])
    @order = @table.order.create(order_params)
    redirect_to order_path(@table)
  end

  private
    def order_params
      params.require(:order).permit(:number, :name, :people)
    end
  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
    @dishes = Dish.select(:id, :name).map { |d| [d.name, d.id] }
    @ingredients = Ingredient.select(:id, :name).map { |d| [d.name, d.id] }
  end

  def create
    @recipe = Recipe.new(recipe_params)
    
    if @recipe.save
      redirect_to @recipe
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def recipe_params
      params.require(:recipe).permit(:name, :dish_id, :ingredient_id, :quantity)
    end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  def index
    @tables = Table.all
  end

  def show
    @table = Table.find(params[:id])
  end

  def new
    @table = Table.new
  end

  def create
    @table = Table.new(ingredient_params)
    
    if @table.save
      redirect_to @table
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @table = Table.find(params[:id])
  end

  def update
    @table = Table.find(params[:id])

    if @table.update(ingredient_params)
      redirect_to @table
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @table = Table.find(params[:id])
    @table.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def ingredient_params
      params.require(:table).permit(:number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/recipe_ingredients_helper.rb
module RecipeIngredientsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/dishes/_form.html.erb
<%= form_with model: dish do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %><br>
    <% dish.errors.full_messages_for(:name).each do |message| %>
    <div><%= message %></div>
  <% end %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.text_field :price %><br>
    <% dish.errors.full_messages_for(:price).each do |message| %>
    <div><%= message %></div>
  <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dishes/index.html.erb
<h1>Dishes</h1>

<ul>
  <% @dishes.each do |dish| %>
    <li>
      <%= link_to dish.name, dish %>
    </li>
  <% end %>
</ul>

<%= link_to "New Dish", new_dish_path %>

app/views/dishes/new.html.erb
<h1>New Dishe</h1>

<%= render "form", dish: @dish, ingredients: @ingredients %>

app/views/dishes/show.html.erb
<h1><%= @dish.name %></h1>

<p>€<%= @dish.price %></p>

<ul>
  <li><%= link_to "Edit", edit_ingredient_path(@dish) %></li>
  <li><%= link_to "Destroy", ingredient_path(@dish), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<h2> Ingredeints </h2>

<ul>
  <% @recipe_ingredients.each do |ingredient| %>
    <li>
      <p><%= ingredient.name %>
    </li>
    <li>
      <p><%= ingredient.quantity %>kg
    </li>
  <% end %>
</ul>

app/views/home/index.html.erb
<h1>Home#index</h1>
<ul>
<li><%= link_to "Ingredients", "/ingredients" %></li>
<li><%= link_to "Dishes", "/dishes" %></li>
<li><%= link_to "Tables", "/tables" %></li>
<li><%= link_to "Recipes", "/recipes" %></li>
</ul>

app/views/ingredients/_form.html.erb
<%= form_with model: ingredient do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %><br>
    <% ingredient.errors.full_messages_for(:name).each do |message| %>
    <div><%= message %></div>
  <% end %>
  </div>

  <div>
    <%= form.label :quantity %><br>
    <%= form.text_field :quantity %><br>
    <% ingredient.errors.full_messages_for(:quantity).each do |message| %>
    <div><%= message %></div>
  <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Edit Ingredient</h1>

<%= render "form", ingredient: @ingredient %>

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>

<ul>
  <% @ingredients.each do |ingredient| %>
    <li>
      <%= link_to ingredient.name, ingredient %>
    </li>
  <% end %>
</ul>

<%= link_to "New Ingredient", new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render "form", ingredient: @ingredient %>

app/views/ingredients/show.html.erb
<h1><%= @ingredient.name %></h1>

<p><%= @ingredient.quantity %>Kg</p>

<ul>
  <li><%= link_to "Edit", edit_ingredient_path(@ingredient) %></li>
  <li><%= link_to "Destroy", ingredient_path(@ingredient), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

app/views/orders/_form.html.erb
<%= form_with model: order do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %><br>
    <% order.errors.full_messages_for(:name).each do |message| %>
    <div><%= message %></div>
  <% end %>
  </div>

  <div>
    <%= form.label :number %><br>
    <%= form.number_field :number %><br>
    <% order.errors.full_messages_for(:number).each do |message| %>
    <div><%= message %></div>
  <% end %>
  </div>

  <div>
    <%= form.label :people %><br>
    <%= form.text_field :people %><br>
    <% order.errors.full_messages_for(:name).each do |message| %>
    <div><%= message %></div>
  <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Edit Order</h1>

<%= render "form", order: @order %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render "form", order: @order %>

app/views/orders/show.html.erb
<h1><%= @order.number %></h1>

<p><%= @order.name %></p>
<p>For <%= @order.people %></p>

<ul>
  <li><%= link_to "Edit", edit_order_path(@order) %></li>
  <li><%= link_to "Destroy", order_path(@order), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<!--
<h2>Dishes</h2>

<% @orders.dishes.each do |dish| %>
  <li>
    <%= link_to dish.name, dish %>
  </li>
<% end %>

<h2> Add dish </h2>
<%= link_to "Add Dish", new_dish_path %>

-->

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<ul>
  <% @recipes.each do |recipe| %>
    <li>
      <%= link_to recipe.name, recipe %>
    </li>
  <% end %>
</ul>

<%= link_to "New Recipe", new_recipe_path %>

app/views/recipes/new.html.erb
<h1>Create recipe</h1>

<%= form_with model: @recipe do |form| %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :dish_id %>
    <%= form.select :dish_id, @dishes.each %>
  </div>

  <div>
    <%= form.label :ingredient_id %>
    <%= form.select :ingredient_id, @ingredients.each %>
  </div>

  <div>
    <%= form.label :quantity %>
    <%= form.text_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/show.html.erb
<h1><%= @recipe.dish.name %></h1>
<p><%= @recipe.quantity %></p>
<p><%= @recipe.ingredient.name %></p>

app/views/tables/_form.html.erb
<%= form_with model: table do |form| %>
  <div>
    <%= form.label :number %><br>
    <%= form.text_field :number %><br>
    <% table.errors.full_messages_for(:name).each do |message| %>
    <div><%= message %></div>
  <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tables/edit.html.erb
<h1>Edit Table</h1>

<%= render "form", table: @table %>

app/views/tables/index.html.erb
<h1>Tables</h1>

<ul>
  <% @tables.each do |table| %>
    <li>
      Table <%= link_to table.number, table %>
    </li>
  <% end %>
</ul>

<%= link_to "New Table", new_table_path %>

app/views/tables/new.html.erb
<h1>New Table</h1>

<%= render "form", table: @table %>

app/views/tables/show.html.erb
<h1><%= @table.number %></h1>

<ul>
  <li><%= link_to "Edit", edit_table_path(@table) %></li>
  <li><%= link_to "Destroy", table_path(@table), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>